### ISSUE TITLE
Fix COMB package main to be node compatible build

### ISSUE THREAD

**Issue by mjbrisebois** [Holo-Host/chaperone#6]
`comb/package.json:main` currently points to the web release which is not compatible with Node.js `require(...)`.  This needs to be fixed so the package can be published to NPM.

Chaperone must be updated to import COMB properly for this to be complete.

**Comment by alastairong** [comment]
@zo-el @robbiecarlton Surely this is done?

**Comment by robbiecarlton** [comment]
Yes this is done

**Comment by robbiecarlton** [comment]
@alastairong - yes this is done
