### ISSUE TITLE
Calls to `resolveHostsForHappAgent`  and `assignHost2Agent` are not triggered whenever the currently matched host becomes unavailable

### ISSUE THREAD

**Issue by JettTech** [Holo-Host/chaperone#65]
Issue: If a holoport goes down, chaperone has no way of requesting a different holoport if the websocket connection fails, resulting in a stale happ (unable to make any successful zome calls).  NB: This occurs when other hosts *are* available in KV store.

Steps to reproduce:
1. Create a new hosted identity by signing up with a new email
2. Observe which holoport was chosen and wait for holofuel inbox page to load
3. Turn off hpos current host / remove the current host from happ2host KV store
4. Notice failed zome calls
5. Refresh browser.
6. Notice continued failed zome calls

**Comment by alastairong** [comment]
This is a known design decision with poor UX. We cannot allow web users to connect to a new source chain host as that would lead to a single agent_key having more than 1 source chain. Holochain will then read this as source chain tampering

**Comment by alastairong** [comment]
Leaving this up for context
