### ISSUE TITLE
`assignHost2Agent` does not persist across multiple user sessions

### ISSUE THREAD

**Issue by JettTech** [Holo-Host/chaperone#66]
Issue: Resolver does not connect user to the previously registered host whenever user signs up or logs in, instead it attempts to connect user to a new host. NB: If user is logging back in, he/she will receive an error stating 'HoloError: Wrong Host'.  However, if the user is signing back up (with the same email/pw), the sign-up and connection to a new host is successful.

Steps to reproduce:
1. Create a new hosted identity by signing up with a new email
2. Observe which holoport was chosen
3. Sign Out (or manually delete seed in browser storage)
4. Refresh browser.
5. Try logging in and observe which port is chosen.

**Comment by alastairong** [comment]
resolved in #58
